### ISSUE TITLE
get_status bug parsing automate response

### ISSUE THREAD

**Issue by NickolausDS** [globus-gladier/gladier-xpcs#102]
Response:
```
'stdErr': 'Traceback (most recent call last):\n'
          '  File "/home/beams10/8IDIUSER/DM_Workflows/xpcs8/automate/gladier-xpcs/scripts/get_status.py", line 113, in <module>\n'
          '    if state_has_completed(args.step, flow_states, status):\n'
          '  File "/home/beams10/8IDIUSER/DM_Workflows/xpcs8/automate/gladier-xpcs/scripts/get_status.py", line 75, in state_has_completed\n'
          '    return flow_states.index(current_state) > flow_states.index(flow_state)\n'
          "ValueError: 'input' is not in list\n",
```

The flow completed successfully here: 
https://app.globus.org/runs/c1e29741-23e3-4840-90d9-7bd996fd3bbb/logs

It's likely the output was in a transient state, so whatever triggered the exception probably isn't reflected in the logs above.

**Comment by NickolausDS** [comment]
I believe this one was fixed, and we haven't gotten a similar error since after doing many many runs. Closing.
