### ISSUE TITLE
Status Reporting Bug

### ISSUE THREAD

**Issue by NickolausDS** [globus-gladier/gladier-xpcs#89]
get_status.py returned an exception when checking status on the flow in the corr state. 

[ACDC link](https://acdc.alcf.anl.gov/xpcs/detail/globus%253A%252F%252F74defd5b-5f61-42fc-bcc4-834c9f376a4f%252FXPCSDATA%252FAutomate%252FG189_PEO_5kDA_S20WtNP_SAMP2_TEMPRAMP_L2Mq0_080C_att03_002_0001-5000/)
Name: G189_PEO_5kDA_S20WtNP_SAMP2_TEMPRAMP_L2Mq0_080C_att03_002
Run id: https://app.globus.org/runs/35c405c0-79d2-418d-afe0-228e7f6c8e33
```
'stdErr': 'Traceback (most recent call last):\n'
                                                                                       '  File "/home/beams10/8IDIUSER/DM_Workflows/xpcs8/automate/gladier-xpcs/scripts/get_status.py", line 113, in <module>\n'
                                                                                       '    if state_has_completed(args.step, flow_states, status):\n'
                                                                                       '  File "/home/beams10/8IDIUSER/DM_Workflows/xpcs8/automate/gladier-xpcs/scripts/get_status.py", line 75, in state_has_completed\n'
                                                                                       '    return flow_states.index(current_state) > flow_states.index(flow_state)\n'
                                                                                       "ValueError: 'input' is not in list\n",
```

**Comment by NickolausDS** [comment]
Another one here: 
DM ID: `0cf8dfe8-92e0-4829-8080-b50b5ea116df`
```
'Traceback (most recent call last):\n'
                                                                                               '  File "/home/beams10/8IDIUSER/DM_Workflows/xpcs8/automate/gladier-xpcs/scripts/get_status.py", line 113, in <module>\n'
                                                                                               '    if state_has_completed(args.step, flow_states, status):\n'
                                                                                               '  File "/home/beams10/8IDIUSER/DM_Workflows/xpcs8/automate/gladier-xpcs/scripts/get_status.py", line 75, in state_has_completed\n'
                                                                                               '    return flow_states.index(current_state) > flow_states.index(flow_state)\n'
                                                                                               "ValueError: 'input' is not in list\n",

```

**Comment by NickolausDS** [comment]
Duplicate of #102
